apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
  ports:
    - name: http-api
      port: {{ .Values.service.port.api }}
      targetPort: api