########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  annotations: {}

  cluster:

    istio:
      enabled: false

    pdb:
      enabled: false

  debug: false

  image:
    pullPolicy: Always
    pullSecrets: []
    registry: ${docker.registry}
    repository: ${docker.repository}
    common: ${docker.common}

  metrics:
    scrape:
      interval: 60s
      timeout: 60s
    servicemonitor:
      enabled: false

  security: {}

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-repository-alfresco-share

image:
  name: ${docker.edu_sharing.community.common.alfresco.share.name}
  tag: "${docker.edu_sharing.community.common.alfresco.share.tag}"

########################################################################################################################

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPU: 80

########################################################################################################################

service:

  port:
    api: 8080

ingress:

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/app-root: /share

  hosts:
    - share.127.0.0.1.nip.io

  tls: []
  #  - secretName: edusharing-repository-tls
  #    hosts:
  #    - repository.127.0.0.1.nip.io

  paths:
    - /share

config:

  jvm:
    ram:
      minPercentage: "90.0"
      maxPercentage: "90.0"

  metrics:
    enabled: true
    relabelings: []

  override: ""

########################################################################################################################

debug: false

########################################################################################################################

nodeAffinity: {}

tolerations: []

########################################################################################################################

podAnnotations: {}

podSecurityContext:

  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsUser: 1000

########################################################################################################################

terminationGracePeriod: 120

startupProbe:

  failureThreshold: 30
  initialDelaySeconds: 0
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

########################################################################################################################
