version: '3.7'

services:

  services-rendering:
    image: "${docker.repository}/edu_sharing-community-deploy-installer-services-rendering-scripts-${os.distribution}-${os.codename}:${docker.tag}"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING_SERVICE_PORT:-9100}:80"
    volumes:
      - "./services/rendering/.env:/opt/edu-sharing/.env"
    depends_on:
      - repository
