services:

  rendering-database:
    image: "${docker.registry}/${docker.image}-postgresql:${docker.tag}"

  rendering-service:
    image: "${docker.registry}/${docker.image}-rendering-service:${docker.tag}"

  rendering-service-init:
    image: "${docker.registry}/${docker.image}-rendering-service:${docker.tag}"
