########################################################################################################################
# GLOBAL
########################################################################################################################

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing-rendering

########################################################################################################################
# DEPENDENCY
########################################################################################################################

edusharing_rendering_postgresql:

  enabled: ${chart.edusharing_rendering_postgresql.enabled}

  nameOverride: &postgresqlNameOverride edusharing-rendering-postgresql

  service:
    port:
      api: &postgresqlServicePortApi 5432

  config:

    database: &postgresqlConfigDatabase rendering
    username: &postgresqlConfigUsername rendering
    password: &postgresqlConfigPassword rendering

########################################################################################################################

edusharing_rendering_rediscluster:

  enabled: ${chart.edusharing_rendering_rediscluster.enabled}

  nameOverride: &redisclusterNameOverride edusharing-rendering-rediscluster

  service:
    port:
      api: &redisclusterServicePortApi 6379

########################################################################################################################

edusharing_rendering_service:

  enabled: ${chart.edusharing_rendering_service.enabled}

  config:

    cache:
      host: *redisclusterNameOverride
      port: *redisclusterServicePortApi

    database:
      host: *postgresqlNameOverride
      port: *postgresqlServicePortApi
      database: *postgresqlConfigDatabase
      username: *postgresqlConfigUsername
      password: *postgresqlConfigPassword

########################################################################################################################
