apiVersion: v2

name: edusharing_community_rediscluster
description: edusharing_community_rediscluster

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"