version: '3.4'

services:

  repository:
    image: "${docker.image}-repository-installer-scripts-debian-bullseye:${docker.tag}"
    environment:
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
      REPOSITORY_SERVICE_HOST_EXTERNAL: "${REPOSITORY_SERVICE_HOST:-localhost}"
      REPOSITORY_SERVICE_HOST_INTERNAL: "repository"
      REPOSITORY_SERVICE_PORT_EXTERNAL: "${REPOSITORY_SERVICE_PORT:-8100}"
      REPOSITORY_SERVICE_PORT_INTERNAL: "${REPOSITORY_SERVICE_PORT:-8100}"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT:-8100}:80"

  rendering:
    image: "${docker.image}-rendering-installer-scripts-debian-bullseye:${docker.tag}"
    environment:
      RENDERING_DATABASE_PASS: "${RENDERING_DATABASE_PASS:-rendering}"
      RENDERING_DATABASE_USER: "${RENDERING_DATABASE_USER:-rendering}"
      RENDERING_SERVICE_HOST_EXTERNAL: "${RENDERING_SERVICE_HOST:-localhost}"
      RENDERING_SERVICE_HOST_INTERNAL: "rendering"
      RENDERING_SERVICE_PORT_EXTERNAL: "${RENDERING_SERVICE_PORT:-9100}"
      RENDERING_SERVICE_PORT_INTERNAL: "${RENDERING_SERVICE_PORT:-9100}"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
      REPOSITORY_SERVICE_HOST: "repository"
      REPOSITORY_SERVICE_PORT: "${REPOSITORY_SERVICE_PORT:-8100}"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING_SERVICE_PORT:-9100}:80"
    depends_on:
      - repository
