version: '3.4'

services:

  repository:
    image: "${docker.image}-repository-installer-scripts-debian-bullseye:${docker.tag}"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT:-8100}:80"
    volumes:
      - ".env.repository:/opt/alfresco/.env"

  rendering:
    image: "${docker.image}-rendering-installer-scripts-debian-bullseye:${docker.tag}"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING_SERVICE_PORT:-9100}:80"
    volumes:
      - ".env.rendering:/opt/rendering/.env"
    depends_on:
      - repository
