{{- if .Values.global.patroni.enabled }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ .Values.global.patroni.name }}
  labels: {{ include "edusharing_postgresql.labels" . | nindent 4 }}
annotations:
  prometheus.io/path: "/metrics"
  prometheus.io/port: "9114"
  prometheus.io/scrape: {{ .Values.sidecar.metrics.enabled | quote }}
  sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
spec:
  databases:
  {{ .Values.config.database }}: {{ .Values.config.username | quote }}
  teamId: {{ .Values.global.patroni.team | quote }}
  users:
    {{ .Values.config.username }}:
      - createdb
  numberOfInstances: {{ .Values.global.patroni.replicas }}
  patroni:
    synchronous_mode: {{ .Values.global.patroni.syncronous.enabled }}
    synchronous_mode_strict: {{ .Values.global.patroni.syncronous.strict }}
  postgresql:
    version: {{ .Values.global.patroni.postgres | quote }}
    parameters:
      {{- with .Values.config.extra }}
      {{ toYaml . | indent 6 }}
      {{- end }}
      listen_addresses: "{{ if .Values.global.cluster.istio.enabled }}127.0.0.1{{ else }}0.0.0.0{{ end }}"
  volume:
    size: {{ .Values.persistence.data.spec.resources.requests.storage }}
    {{- if or .Values.global.cluster.storage.data.spec.storageClassName .Values.persistence.data.spec.storageClassName }}
    storageClass: {{ default .Values.global.cluster.storage.data.spec.storageClassName .Values.persistence.data.spec.storageClassName }}
    {{- end }}
  {{- with .Values.resources }}
  resources: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.sidecar.metrics.enabled }}
  sidecars:
  - name: metrics
    image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/edusharing-postgresql_exporter:{{ .Values.global.image.tag }}
    args:
    - --disable-settings-metrics
    - --web.listen-address={{ if .Values.global.cluster.istio.enabled }}127.0.0.1{{ end }}:9114
    - --web.telemetry-path=/metrics
    env:
    - name: DATA_SOURCE_URI
      value: $(POD_NAME)/postgres?sslmode=disable
    - name: DATA_SOURCE_USER
      value: $(POSTGRES_USER)
    - name: DATA_SOURCE_PASS
      value: $(POSTGRES_PASSWORD)
    - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
      value: "true"
    {{- with .Values.sidecar.metrics.resources }}
    resources: {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}